### ISSUE TITLE
GitHub Org

### ISSUE THREAD

**Issue by jdev082** [FossAV/FossAV#14]
You should move this to a github org.

**Comment by Piggo4676** [comment]
idk how to... I have never propperly used github before. teach me the way...

**Comment by jdev082** [comment]
https://www.youtube.com/watch?v=dhxTFy19YIs

**Comment by Piggo4676** [comment]
Could I please use your email for the Company email?

**Comment by UniqueName12345** [comment]
Done!

**Comment by Piggo4676** [comment]
Can I transfer ownership of the email to someone else?

**Comment by UniqueName12345** [comment]
> Can I transfer ownership of the email to someone else?

wdym
