### ISSUE TITLE
Who Will Take Ownership Of The Email?

### ISSUE THREAD

**Issue by Piggo4676** [FossAV/FossAV#15]
Does anyone want to take ownership of the fossantivirus@gmail.com email? All I ask is that they let me know if anyone sends a message or somethings. If anyone says yes, I will give them the password securely. I also ask that they do NOT USE THE EMAIL FOR OTHER PURPOSSES!!!! Please only use the email for, well, emailing. nothing else.

**Comment by ninjamar** [comment]
How about you?

**Comment by Piggo4676** [comment]
no. I don't trust myself and also I just don't want to have it. Do you want it? you don't actually need to do anything i guess, just have it sitting there incase.

**Comment by ninjamar** [comment]
What would the email be for?

**Comment by Piggo4676** [comment]
Just any business things/decisions that need an email, in other words, almost nothing.

**Comment by Piggo4676** [comment]
Please, someone.

**Comment by ninjamar** [comment]
How about not using an email?

**Comment by Piggo4676** [comment]
> How about not using an email?

Wait can people not see the email I use to make the organisation?
